[feature_config]
is_alive = one_hot:1:eq
belong_to_main_camp = one_hot:1:eq
location_x = min_max:-41000:41000
location_z = min_max:-41000:41000
relative_location_x = min_max:0:1
relative_location_z = min_max:0:1
hp_rate = min_max:0:1

# Additional Feature from ActorState
is_main_camp = one_hot:1:eq
attack_range = min_max:0:15000
attack_target = one_hot:1:eq
kill_income = min_max:0:200
sight_area = min_max:0:15000
visibility = one_hot:1:eq

; Actor values
phy_atk = min_max:0:10000
phy_def = min_max:0:500
mov_spd = min_max:0:10000

[feature_functions]
is_alive = is_alive
belong_to_main_camp = belong_to_main_camp
location_x = get_normal_organ_location_x
location_z = get_normal_organ_location_z
relative_location_x = relative_location_x
relative_location_z = relative_location_z
hp_rate = get_hp_rate

# Additional mapping functions
is_main_camp = is_main_camp
attack_range = get_attack_range
attack_target = get_attack_target
kill_income = get_kill_income
sight_area = get_sight_area
visibility = get_visibility
phy_atk = get_phy_atk
phy_def = get_phy_def
mov_spd = get_mov_spd
